language: ruby
services:
  - mongodb
  - elasticsearch
rvm:
  - 2.1.4
notifications:
  irc:
    channels:
    - irc.freenode.net#openaddresses
    template:
    - "%{repository} %{branch} - %{message} %{build_url}"
    on_success: change
    on_failure: always
