ruby '2.1.4'
#ruby-gemset=sortingoffice

source 'https://rubygems.org'

gem 'rspec'
gem 'database_cleaner'
gem 'pry'
gem 'factory_girl'
gem 'timecop'
gem 'coveralls'

gem 'httparty'
gem 'mongoid'
gem 'mongoid-tree'
gem 'mongoid_token'
gem 'mongoid_geospatial'
gem 'rake'
gem 'nokogiri'
gem 'rubyzip'
gem 'uk_postcode'
gem 'mongoid_address_models', github: "OpenAddressesUK/mongoid_address_models"
gem 'mongoid-elasticsearch'
gem 'dotenv'
gem 'breasal'
gem 'platform-api'
gem 'sinatra'
gem 'geokit'
gem 'colorize'
gem 'unicorn'
gem 'dotenv'
gem 'iron_mq'
